version: "2"
services:
  grpc-server:
      command: python server.py
      image: insecure_grpc-server
      networks:
       - grpc
      environment:
       - SERVICE_NAME=grpc-server

  grpc-client:
      command: python client.py grpc-server:50051
      image: insecure_grpc-client
      networks:
       - grpc
networks:
  grpc:
